version: "3.9"
services:
  django:
    image: awura_web:latest
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:54101"
    ports:
    - "54101:54101"